### PR TITLE
Simulink Model Removal

### PR DESCRIPTION
**Pull request by dack-fe**
Removed the old and non-Frost folders and projects

### CODE REVIEW

**Comment by dack-fe** [comment]
Do we want to move the following to a new repo called *Old Projects* or something similar:
1. HA_sys8?
2. JMAP Speech Enhancement Project?
3. Acoustic Delay?

Are any of these projects relevant? Working? Worth Keeping?

**Comment by rksnider** [comment]
I would put them under Old Projects as you suggest.  HA_sys8 is the old
hearing aid based on band-pass FIR filters.   I can't remember what the
other two are.

Ross

**Comment by fe-tdavis** [comment]
I agree, let's put them in a new repo.

**Comment by tvannoy** [comment]
JMAP Speech Enhancement was an intern project that was never quite finished. Acoustic Delay Buffer was basically just a dual port RAM for an earlier beamforming project; it was created in Intel's DSP Builder. Both of those projects can be deleted.

Somebody (most likely @rksnider) *might* want to look at HA_sys8 in the future for some reason. However, we don't technically need to keep anything in a separate repo because we can always access them in the git history if needed (in particular, this PR would be an easy place to start to find relevant commits). If we do put anything in an "Old Projects" repo, I think the repo should be private and/or archived.

**Comment by fe-wickham** [comment]
If the only old model we want to keep is HA_sys8, I'd be preferential to just leaving it where it is and adding a ReadMe to it explaining it to be a preserved relic. That seems better than making a whole repo, private or otherwise, over a single old model. (Git history is technically an option, but given the intended potential users seems less viable)

**Review by fe-wickham — APPROVED** [review]
Good job getting rid of the old stuff

**Comment by dack-fe** [comment]
`HA_sys8` was left in the current folder. More discussion can be had during the merge into Dev. For now, we can focus on updating the remaining projects.

**Comment by tvannoy** [comment]
> More discussion can be had during the merge into Dev.

Just throwing this out here so I don't forget. Keeping `HA_sys8` sounds good, but we should consider giving it a better name when merging into dev.

**Comment by rksnider** [comment]
I agree

**Comment by rksnider** [comment]
HA_sys8 can be removed.  This was really just to get a filtering system
working quickly.  Modern hearing aids use the frequency domain, i.e. FFT
approach.

Ross

**Comment by rksnider** [comment]
If we keep it, we should call it FIR_system.

Ross

**Pull request merged**
