### PR TITLE
Bitcrusher README

### PR DESCRIPTION
**Pull request by tvannoy**
Added README and block diagram; also deleted an old model. I don't think I have access to the diagrams we created for the website, so I used one from my thesis; we can change that so all of our block diagrams match, if we want.

Working towards #79

### CODE REVIEW

**Review by fe-wickham — APPROVED** [review]
Looks good to me

**Review by fe-tdavis — CHANGES_REQUESTED** [review]
Looks good overall.  I shared the draw.io project I made for the sound effect block diagrams.  Could you update the color scheme for your schematic based on that?  I like the empty boxes around the effects, so maybe we should standardize to the AudioLogic color scheme with that?  [Echo](https://github.com/fpga-open-speech-tools/simulink_models/tree/updateNValidate/models/echo) is an example of a filled version.

**Review by fe-tdavis — APPROVED** [review]

**Comment by tvannoy** [comment]
@fe-tdavis thanks for updating the block diagram and fixing the copy/paste error from the echo readme... I will use the draw.io project you shared for the rest of the readmes. I will have more time this evening to continue on documentation. I'm into standardizing the diagrams based on the updated bitcrusher -- looks good!

**Comment by fe-tdavis** [comment]
@tvannoy You're welcome and that sounds great!  I think things are really shaping up.  I put the hex colors for the AudioLogic color scheme we've been using in the project, so feel free to try different things out as well.

**Pull request merged**
