### PR TITLE
sound effects README

### PR DESCRIPTION
**Pull request by tvannoy**
Do we want a block diagram for this as well? Or do we just let people refer to the linked project READMEs?

#79

### CODE REVIEW

**Comment by fe-tdavis** [comment]
I think we can just let people refer to the project READMEs for the full effect.  The formatting on the complete block diagram was problematic before and made the blocks difficult to read.  It would probably be worth putting one together just to see how it looks on Github though.

**Review by fe-tdavis — CHANGES_REQUESTED** [review]
We should add a small implementation section that talks about the model referencing of the design.  Otherwise, it's looking good.

**Review by tvannoy — COMMENTED** [review]
A brief description of model referencing was added, and some outdated/incorrect names in the model were changed. 
I don't really know much of details about model referencing, as I wasn't involved in it, so hopefully the description is accurate/sufficient.﻿

**Comment by dack-fe** [comment]
@fe-wickham Can you take a quick look at this?

**Review by fe-wickham — APPROVED** [review]
Looks good 👍

**Review by fe-tdavis — COMMENTED** [review]
Looks good

**Pull request merged**
