### PR TITLE
DS-Beamformer Docs

### PR DESCRIPTION
**Pull request by tvannoy**
Towards #79

### CODE REVIEW

**Comment by tvannoy** [comment]
The implementation block diagram was created with draw.io, but it is not currently shared with anyone. Let me know if/how you want me to share it.

**Review by dack-fe — CHANGES_REQUESTED** [review]
The images that were added are for the beamformer. Do we have an image or block diagram for the Beamer?

**Comment by tvannoy** [comment]
> Where are the new images going?

@fe-tdavis Is there a common Drive folder where we are keeping all of the draw.io files?

**Comment by fe-tdavis** [comment]
@tvannoy Yes, there is a drive folder.  I just shared a link with you

**Comment by tvannoy** [comment]
The beamforming draw.io diagram has been added to the drive folder. The other image was made in inkscape, so the svg in this PR is the original source file.

**Review by dack-fe — APPROVED** [review]
Beamformer Read Me looks good

**Pull request merged**
