### PR TITLE
Noise suppression updates

### LINKED ISSUE #70: Noise Suppression Properly Verify
The Noise Suppression model contains additional scripts - https://github.com/fpga-open-speech-tools/simulink_models/tree/dev/models/noise_suppression/MATLAB_scripts

What are these scripts? Can they be removed?

### PR DESCRIPTION
**Pull request by dack-fe**
Closes #70 
 - Added Reference Model with vector inputs and output broken out
 - Added Verification

### CODE REVIEW

**Review by tvannoy — COMMENTED** [review]
Looks good to me, especially if we don't mind that the MATLAB simulation doesn't exactly match the Simulink model. My best guess is that the differences are due to data type issues.

**Comment by fe-wickham** [comment]
> Looks good to me, especially if we don't mind that the MATLAB simulation doesn't exactly match the Simulink model. My best guess is that the differences are due to data type issues.

It looks like there might be a little bit more going on than data type, however we are presently using the verification as more for comparison on this model than claiming that is exactly what we implemented.

**Review by fe-wickham — APPROVED** [review]
I like the updates and just added a commit so right channel has just as much validation and plotting as left channel

**Comment by tvannoy** [comment]
> It looks like there might be a little bit more going on than data type, however we are presently using the verification as more for comparison on this model than claiming that is exactly what we implemented.

You are right. I just had another look at `adaptiveWienerFilt`, and it was using the incorrect calculations for mean and variance; ironically, both versions of mean/variance calculations were in the code... :facepalm: 

The verification results are *much* closer now, though still not perfect. I think the verification code now actually does the same calculations as the simulink model. I now realized that the Simulink implementation seems to be ignoring the `if variance < noiseVariance variance = 0` condition from the original algorithm. Oh well.

**Review by tvannoy — APPROVED** [review]
MATLAB verification is much closer now﻿

**Pull request merged**
